source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target ‘JingChengWirelessOrderForDishes’ do
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'AFNetworking', '~> 3.1.0'
end